### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by MrksKwsnck** [owncloud/bookmarks#145] opened 2015-04-30 16:08 UTC
I just wanted to export my bookmarks by clicking on the **Export** button. All I got back was a PHP fatal error:

> **Fatal error**: Class 'OCA\Bookmarks\Controller\Rest\OCA\Bookmarks\Controller\Lib\Helper' not found in /path/to/my/owncloud/apps/bookmarks/controller/rest/bookmarkcontroller.php on line 242

I am running my own *ownCloud* 8.0.2 (stable) instance. And the bookmarks app version is 0.4 which I installed from [here](https://apps.owncloud.com/content/show.php/Bookmarks+8.0?content=168710).

So how hard is it to fix that issue?

**Comment by MarekK82** [comment] 2015-04-30 17:16
Well, I just found myself the cause and a solution. The namespace in the call of the Helper class could not be resolved. Anyway, I created a pull request https://github.com/owncloud/bookmarks/pull/146 looking forward to get merged.

**Comment by jmcclelland** [comment] 2015-11-23 17:53
This issue seems closed, however, the fix does not seem to be merged. Is there a reason for that?

**Comment by MarekK82** [comment] 2015-11-23 21:36
In fact the pull request https://github.com/owncloud/bookmarks/pull/146 is still open.

**Comment by blizzz** [comment] 2016-06-12 09:26
#146 was merged

**Closed by blizzz** 2016-06-12 09:26 UTC
