### ISSUE TITLE
multiple tags dont work

### ISSUE THREAD

**Issue by dnano91** [owncloud/bookmarks#20] opened 2013-06-11 11:56 UTC
![shot-2013-06-11_13-52-27](https://f.cloud.github.com/assets/4669823/636714/c05e6744-d28d-11e2-8271-af84e9833f64.jpg)

when i add a bookmark with multiple tags, this is how it ends up in owncloud:
![shot-2013-06-11_13-52-47](https://f.cloud.github.com/assets/4669823/636717/daa029d0-d28d-11e2-9f9c-8e13034574e4.jpg)

and when i search for the second tag:
![shot-2013-06-11_13-52-57](https://f.cloud.github.com/assets/4669823/636719/e900a7e8-d28d-11e2-9d37-fada8c250fbe.jpg)

**Comment by blizzz** [comment] 2015-07-08 12:56
Probably fixed with https://github.com/owncloud/bookmarks/pull/68, at least works since OC 7. Please reopen, if you still have the issue.

Mind, there is an regression were adding tags is missing, for this follow there https://github.com/owncloud/bookmarks/issues/127

**Closed by blizzz** 2015-07-08 12:56 UTC
Labels: bug
